### ISSUE TITLE
Self-Service BI Content missing

### ISSUE THREAD

**Issue by anniexudan** [microsoft/PartnerResources#14]
I would like to contribute the partner learning plan for the Self-Service BI (aka Power BI) learning plan (I have already created in the attachment). Please add a session where I can contribute to the readme

**Comment by tadthompson** [comment]
The Power BI Learning plan is here:
https://github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Business%20Applications/Power%20Platform/Modern%20Analytics.md
