### ISSUE TITLE
Broken links for In-person Instructor Led pages

### ISSUE THREAD

**Issue by petertuton** [microsoft/PartnerResources#17]
Many of the links to "In-person Instructor Led" pages are broken, e.g. Cloud to Cloud Migration (there are many more).

**Comment by bhitney** [comment]
Confirmed that in Cloud to Cloud migration (github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Azure/Infrastructure/Cloud%20to%20Cloud%20Migration.md) most of the expert-level links that are instructor led are 404.

Confirmed that in VMWare Migration (github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Azure/Infrastructure/VMWare%20Migration.md) those expert-level instructor led links are 404.

Likely others, but will rely on team to check their own areas.  Thanks for raising.

**Comment by Jeep-Girl** [comment]
We've notified across the SET re links and to be checking across LPR's. If you cannot find where the new links are please do best effort to do some discovery. Raise issues SPECIFICALLY on which Learning Plan resource if there are errors and you cannot determine path forward (i.e. did due diligence in finding updated material but could not find, etc.).
