### ISSUE TITLE
Broken Links for Modern Data Warehouse

### ISSUE THREAD

**Issue by david-okeefe** [microsoft/PartnerResources#20]
The links to the "Introducing Azure Synapse Analytics (Ignite session / 1 hour)" session and the link to "Azure Partner Tech Talks - Modern Data Warehouse" under the Fundamentals learning path on Modern Data Warehouse (https://github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Azure/Data%2C%20Analytics%2C%20and%20AI/Modern%20Data%20Warehouse.md) are broken.

**Comment by bhitney** [comment]
Fixed -- thank you!
