### ISSUE TITLE
Add Icons/Emojis next to each link of the learning plan to identify content type

### ISSUE THREAD

**Issue by husamhilal** [microsoft/PartnerResources#200]
At each learning plan add add Icons/Emojis next to each link **identify content type: Video, Audio, Text, Diagram, etc...**
This will help viewers quickly identify the content type and encourage them to move forward and learn further.

**Comment by ZacharyRiffle** [comment]
Are you still interested in pursuing this idea Husam?

**Comment by husamhilal** [comment]
> Are you still interested in pursuing this idea Husam?

Thanks Zach, If we make it a standard. Yes, I'll be happy to implement it at AVS page. But wanted to make sure we all agree on it?

**Comment by ZacharyRiffle** [comment]
Hi Husam,

Can I schedule 10 or 15 minutes to discuss more?

Zach

**Comment by husamhilal** [comment]
Of course! Happy to collaborate!

**Comment by ZacharyRiffle** [comment]
Hi Husam, I am closing this issue. The underlying objective of this issue, to "help viewers quickly identify content type and encourage them to move forward and learn further", has to some extent already been accomplished. The repository has made great strides in becoming more visually appealing and consumable. We have expanded the use of emojis, graphics, visuals, etc. and while emojis per content type are not implemented at scale, it will remain a best practice for **all** future pages.

**Comment by husamhilal** [comment]
Great, thanks a lot @ZacharyRiffle ! Cheers!
