### ISSUE TITLE
Create specific short URLs (aka.ms) for each Learning Plan (i.e.: aka.ms/OCPTODO/AVS for Azure VMware Solution)

### ISSUE THREAD

**Issue by husamhilal** [microsoft/PartnerResources#208]
Would it be possible to create specific aka.ms urls for certain learning plans in TODO? for example, for AVS, something like aka.ms/ocptodo/avs  or aka.ms/ocptodo/azure/avs

**Comment by bhitney** [comment]
Sure -- we currently do this for Modern Analytics Academy (aka.ms/maa); this could be either to the root of a plan, a search result, tag, etc. We don't change permalinks unless there's a dire need, so it should be ok to create any aka.ms links you'd need.
