### ISSUE TITLE
Improve Machine Learning learning plan 

### ISSUE THREAD

**Issue by laurentran** [microsoft/PartnerResources#215]
-reorganize resources 
-pair down existing resources that are redundant
-add video(s)
-add additional relevant content

**Comment by bhitney** [comment]
Hi Lauren -- good ideas!  Do you have specific changes in mind or are you able to make any required changes/additions?  Any contributions would be appreciated!

**Comment by laurentran** [comment]
Hey Brian! My team is working on this now, and we'll submit a PR probably next week!

**Comment by bhitney** [comment]
That's great, your expertise is appreciated!  We're happy to help any way we can, just reach out.
