### ISSUE TITLE
DevOps Plan Link error

### ISSUE THREAD

**Issue by bhitney** [microsoft/PartnerResources#22]
The DevOps Community Content link in the DevOps plan seems to be behind a reg wall I can't access.

**Comment by gregdegruy** [comment]
@bhitney which of these links from here?https://github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Azure/AppDev/DevOps.md

![image](https://user-images.githubusercontent.com/8151045/97900033-f994ba00-1cee-11eb-9e4e-d72a13317dc4.png)

**Comment by bhitney** [comment]
Sorry for the late reply!  It's the DevOps community content seems to link to a [Sharepoint site](https://microsofteur.sharepoint.com/teams/1ServicesDevOps) that's not externally accessible... I'll remove from the plan, but can be added back in if in error.
