### ISSUE TITLE
Right hand nav menu and permailink automation

### ISSUE THREAD

**Issue by gregdegruy** [microsoft/PartnerResources#239]
- [ ] As a part of GitHub build use tags to generate the page menu items `#### {% raw %}[DevOps](devops){% endraw %}
`. This can be done using some script based [on these docs](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_content_reuse.html) or include statement to populate a page based on the tags from that page.
Example: Display all learning plans with Azure App Dev tags.

or

- [ ] Move nav items to nest menu that is N levels deep.

**Comment by bhitney** [comment]
completed
