### ISSUE TITLE
Modify Industry nav to match Industry index.md

### ISSUE THREAD

**Issue by tadthompson** [microsoft/PartnerResources#250]
Currently only Healthcare shows in the Nav, but the page shows all industry LPs

**Comment by gregdegruy** [comment]
Fixed in commit [1669d7bbbd9344d0e10e30025e107578cdc64a27](https://github.com/microsoft/PartnerResources/commit/1669d7bbbd9344d0e10e30025e107578cdc64a27) "Added industries to table of contents".
