### ISSUE TITLE
Link is broken when going back from AVS-Labs page to AVS main page

### ISSUE THREAD

**Issue by husamhilal** [microsoft/PartnerResources#271]
The link is broken going back from Table of Content to AVS main page, the reason is the extra forward slash appended to the URL.
This is the problem (notice the forward slash at the end)
https://microsoft.github.io/PartnerResources/azure/infrastructure/azure-vmware-solution/
This is supposed to be the solution:
https://microsoft.github.io/PartnerResources/azure/infrastructure/azure-vmware-solution

![image](https://user-images.githubusercontent.com/11361105/130529985-e4b69c7d-b8e5-4c43-891d-de9efeca0959.png)

In addition, in the breadcrumb link, it should have **vmware** as: **VMware**

**Comment by bhitney** [comment]
There are a couple of challenges here. Fundamentally, the breadcrumbing is designed to work within the defined toc.yml in the data folder. If there are additional folders it doesn't know about (as is the case here) rendering can be wrong -- it won't know proper case, etc. I moved this functionality to _includes/breadcrumb.html for future work to improve this. One possible solution is to add the folder structure to the lab in toc.yml, and modify breadcrumb.html to work recursively. 

Another possible solution is to simply add "showbreadcrumb: false" in the front matter (top of page, like w/ permalink and tags). That removes the breadcrumb from the page, as it's not needed on some pages.

The best solution, however, I think is to move the lab to the new hands-on / skilling section, which is designed for workshop/lab content where there are subpages. 

I'll discuss these w/ you. 👍
