### ISSUE TITLE
Missing Financial Services

### ISSUE THREAD

**Issue by david-okeefe** [microsoft/PartnerResources#303]
The industry documentation is missing Financial Services resources.

**Comment by david-okeefe** [comment]
We should minimally include a link to the Cloud for Financial Services overview presented by Thomas Mathew on April 13.

https://msuspartners.eventbuilder.com/TKEFinancialServicesPartners

**Comment by tadthompson** [comment]
We are going to be doing a big push on updating learning plans in the next few weeks

**Comment by tadthompson** [comment]
Strange, we are missing Financial Services all together. It was fairly built out and has disappeared/deleted

**Comment by tadthompson** [comment]
Completed
