### ISSUE TITLE
Broken Links in Cloud to Cloud Migrations

### ISSUE THREAD

**Issue by david-okeefe** [microsoft/PartnerResources#35]
All of the In-Person Training links in the Expert section of Cloud to Cloud Migrations lead to 404 error pages.

https://github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Azure/Infrastructure/Cloud%20to%20Cloud%20Migration.md

**Comment by jeffstof** [comment]
Thanks David for submitting.  I removed the broken links and submitted a pull request. The content will be updated shortly!
