### ISSUE TITLE
Where is CDP (Customer Insights)?

### ISSUE THREAD

**Issue by johnwiese-ms** [microsoft/PartnerResources#37]

**Comment by johnwiese-ms** [comment]
We don't have a plan setup for this, could we get a template setup and I will add a bunch of stuff to the plan?

**Comment by tadthompson** [comment]
I had actually just created one about 45 minutes ago :-)
I copied from Customer Service so it mostly needs to be changed

**Comment by tadthompson** [comment]
Customer Insights Learning Plan created
