### ISSUE TITLE
GitHub Certifications link is broken with 404

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/PartnerResources#374]
The "GitHub Certifications coming soon" link on the https://microsoft.github.io/PartnerResources/azure/appdev/devops page is broken. Looks like that page is no longer there. Are GitHub Certifications really coming soon, or has this been cancelled?

**Comment by bhitney** [comment]
This is a good question and for the time being, will remove the link until we know if there are updates (haven't found anything yet).
