### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by TX-RX** [microsoft/PartnerResources#404]
Question on: https://github.com/microsoft/PartnerResources/tree/master/_docs/Azure/Data, Analytics, and AI/Microsoft Purview.md

Under the Fundamentals section What is Data Governance link points to content that does not appear to related to data governance. I am not sure if the title is wrong or the link is wrong.

**Comment by bhitney** [comment]
Thank you! It should've linked to the "What is data governance?" session in the academy but the link wasn't formatted correctly -- this should be resolved.
