### ISSUE TITLE
Azure Security Academy feedback

### ISSUE THREAD

**Issue by DeanGross** [microsoft/PartnerResources#521]
Do you have any plans to add content for Defender for Threat Intelligence and/or Defender for External Attack Surface Management?

**Comment by ZacharyRiffle** [comment]
Hello Dean -- while we do not offer content solely dedicated to MDTI and EASM, we do cover aspects or portions of it throughout other sessions. Explore our All About Microsoft Sentinel Threat Intelligence and Investigation and our All About Jupyter Notebooks and Hunting sessions under our Sentinel Academy.
