### ISSUE TITLE
how to install pgtap extension in azure postgres flexible servers

### ISSUE THREAD

**Issue by Niba-nazar** [microsoft/PartnerResources#559]
hi,

I want to add pgtap extension in azure PostgreSQL flexible servers. however, in azure.extensions and shared_preload_libraries I couldn't find it. I tried to open a support ticket for the same, there I found a query 'select * from og_available_extensions;' to check the extension which I require is available in azure flexible servers or not. There I found pgtap version 1.2.0. 

Hence, I tried to create the extension and getting error like below. How can I enable pgtap extension in azure portal?

![image](https://github.com/microsoft/PartnerResources/assets/114569256/8da56e52-b8f5-4c07-8f42-54f2cea4d02a)

```
exp_portnox=> CREATE EXTENSION pgtap;
ERROR:  extension "pgtap" is not allow-listed for "azure_pg_admin" users in Azure Database for PostgreSQL
HINT:  to see the full allow list of extensions, please run: "show azure.extensions;"
```

**Comment by bhitney** [comment]
Looks like this is being tracked here: https://github.com/MicrosoftDocs/azure-docs/issues/112207 so I'll close this issue here.

**Comment by subhrabeh** [comment]
Facing the same issue , the link above is not accessible. Is there a way to use pgtap with azure pgsql flexible server?

**Comment by robertdecaire** [comment]
Also interested in knowing whether this is possible. There should at least be some kind of unit testing library available.
