### ISSUE TITLE
Access issue to Platform Pitch Deck

### ISSUE THREAD

**Issue by johnwildes** [microsoft/PartnerResources#584]
Who do you reach out to when you run into a permissions issue?  I am using my account, which is affiliated with partner central and we're a Microsoft partner, yet I cannot access the slide deck listed here.

https://transform.microsoft.com/modernwork/download?assetname=assets%2FLow%20Code%20%2B%20AI%20Pitch%20Deck.pptx&download=1

On the document listed here.
https://microsoft.github.io/PartnerResources/skilling/d365-academy/business-applications/copilot/powerautomate

How do I request access there doesn't seem to be a way.  I can authenticate to transform.microsoft.com and see resources, but this link and I'm sure others I'm not getting access to.

**Comment by ZacharyRiffle** [comment]
Hi John,

Thank you for opening an issue. We forwarded your question to our colleague who uploaded the slide deck. We will keep you posted.

Zach

**Comment by ZacharyRiffle** [comment]
Hello again John,

We have removed the slide deck and are working towards uploading one that is accessible.

Zach
