### ISSUE TITLE
Question: Academy blocks interchanged for I&A and Endpoint Security modules. 

### ISSUE THREAD

**Issue by akg87** [microsoft/PartnerResources#597]
Question on: https://github.com/microsoft/PartnerResources/tree/master/_docs/Skilling/Microsoft Security Academy/index.md

It looks like the academy blocks in the first figure of this page have been interchanged for identify and access and endpoint security.

**Comment by ZacharyRiffle** [comment]
Thank you for your feedback! The issue was resolved.
