### ISSUE TITLE
Missing financial services and financial server query

### ISSUE THREAD

**Issue by johnpatrickoldfield** [microsoft/PartnerResources#630]
I need to pay for stuff on a fees schedule and the financial services tools required to pay for stuff is missing. 

There seems to be a financial server requirement at the local bank and its not available.
There also seems to be a financial server requirement at the international bank and or local international bank and its not available.
There seems to be a financial server requirement from either or both post graduate retiree parents and it doesn't seem to be available.
There seems to be a financial server requirement from a doctorate sibling however doesn't seem to be available. 
There seems to be a financial server requirement from the local government however doesn't seem to be available.
There seems to be a financial server requirement from the private sector however doesn't seem to be available.
There seems to be a financial server requirement from the future potential employer however doesn't seem to be available.
There seems to be a financial server requirement from a current employer however doesn't seem to be available.
There seems to be a financial server requirement from a previous employer(s) however doesn't seem to be available.
There seems to be a financial server requirement from friends and or friends parents and or friends sibling and or friends partners but there doesn't seem to be available.
There seems to be a financial server requirement from strangers and or unknown/stranger business partners and there doesn't seem to be one available.
There's seems to be a financial sever requirement from cousins and or uncles and or aunts or grand parents and or grand aunts or grand uncles and there doesn't seem to be one available.

Why? Why doesn't the financial server work? It doesn't even say how to configure and or create a financial server other than to sacrifice my personal time and or personal space to another person and or entity type? And none will assist one and or the other without one and or the other where one and or the other is not good enough and goes as far as disgraceful to even ask and or query! I keep getting asked to pay to receive money to pay with and then inferred to ask someone else to ask for money to pay with or go without. Its one of the most frustrating systems I have ever used, its just blocking consulting meetings and purchases on inaccessibility to fees payments allowance mechanisms. There's a backlog of outstanding payments.  https://docs.google.com/spreadsheets/d/1ReaGLeg2fK2Z7IuYkrmhSqnrjq0oy8Qb/edit?usp=drive_link&ouid=113224444166029828866&rtpof=true&sd=true ; https://docs.google.com/spreadsheets/d/1dWz3miggfwuEoIRrXAj4Ylsnzlu0f5Hr4hBIJbRBmNQ/edit ; 

I never learnt anywhere in school and or university how to beg financial server requirements personal for financial where there was previously no requirement to beg from various personal where there an assumption that the job system and or financial system just works. The systems literally tries to force me to negotiate with people to fix financial server issues that shouldn't be financial server issues. Its not soft arguments either its such intense arguments, I would rather use an arguments handler however the arguments handler wasn't really taught much at university. And the "legal" and or law system requires fees payments allowances. The only place I have seen begging is on the streets where the poverty is not regulated and or removed. Until I move to a city town and or suburb and or country where poverty is not allowed. Also there's so many console errors in the browser console? Doesn't say anything in the education system for debugging console errors; https://stackoverflow.com/questions/53319231/how-to-get-javascript-console-error-for-debugging ; https://nodejs.org/api/console.html ; https://developer.chrome.com/docs/devtools/javascript/ ; https://www.w3schools.com/Jsref/met_console_error.asp ; https://www.w3schools.com/js/js_debugging.asp

https://quant.stackexchange.com/questions/29572/building-financial-data-time-series-database-from-scratch ; https://towardsdatascience.com/how-to-build-an-accounting-system-using-sqlite-2ce31f8b8652 ; https://dba.stackexchange.com/questions/83951/financial-database-design ; https://www.janbaskdigitaldesign.com/blogs/building-financial-website-using-wordpress/ ; https://blog.servermania.com/choosing-a-small-business-server ; https://techjury.net/blog/how-to-build-a-server/ ; https://www.businessprotech.com/purchasing-server-for-business/ ; https://www.tableau.com/solutions/finance-analytics ; https://www.itjones.com/blogs/2021/2/8/how-to-setup-a-server-for-a-small-business

https://builtin.com/software-engineering-perspectives/new-programming-languages ; https://www.slant.co/topics/6032/~systems-programming-languages ; https://hackr.io/blog/best-programming-languages-to-learn ; https://www.slant.co/topics/6024/~programming-languages-for-concurrent-programming ; https://www.coursera.org/articles/popular-programming-languages ; https://www.computerscience.org/resources/computer-programming-languages/ ; https://builtin.com/software-engineering-perspectives/best-programming-languages-to-learn ; 

https://stackoverflow.com/questions/65887723/passing-multiple-arguments-and-event-to-event-handler-using-bind ; https://blogs.30dayscoding.com/blogs/react/react-fundamentals/handling-events/passing-arguments-to-event-handlers/ ; https://stackoverflow.com/questions/59338465/passing-arguments-to-event-handlers ; https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/arguments

https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/console-debug-javascript ; https://stackoverflow.com/questions/68159024/does-too-many-console-errors-affect-browser-performance ; https://developer.chrome.com/docs/lighthouse/best-practices/errors-in-console/ ; https://developer.mozilla.org/en-US/docs/Web/API/console

**Comment by johnpatrickoldfield** [comment]
Hello Zachery Riffle

Thanks for your response. Yes, its a shame that its closed.
https://www.jamasoftware.com/requirements-management-guide/requirements-gathering-and-management-processes/what-is-requirements-gathering
; https://www.phase2technology.com/blog/successful-requirements-gathering
This system keeps looping on failed functionality and its difficult to go
round and or past it.

I can't get further than creative writing at the moment, The most I could
do extra is try and create a data flow diagram using those data science
drawings to try and slot in personal types and or job descriptions and then
more accurately defined the request and try and show the recipient a input
requirement. However as its currently worded it doesn't do too much than
highlight a problem statement for designing various tools that plugin to
the relevant financial system. Where's the financial services page that you
refer to?
https://drive.google.com/file/d/1_AJQroOHkpBABvakqzmPlNsnIhltG52-/view?usp=drive_link
I just have these public and or private sector ones and then the public
bank websites the internal login functionality is not very good, it doesn't
even say how to create the finance website. I did try and work it however I
am not sure how to create the wireframe and then the webpage design layout
is very difficult, Maybe I should send the local school and or university a
prize question to design a bank dashboard and or interface that includes
the relevant bank and or finance dashboards and job descriptions from a
real perspective. As opposed to analytics only and no services
accessibility.
https://www.lucidchart.com/pages/examples/data-flow-diagram-software ;
https://online.visual-paradigm.com/diagrams/features/dfd-maker/ ;
https://learn.microsoft.com/en-us/training/modules/tm-use-recommended-tools-to-create-a-data-flow-diagram/
; its private information though
https://www.lucidchart.com/pages/decision-tree.

Where is the financial services page? Do I have to create one or is there
an existing one if there is an existing financial services page?

https://en.wikipedia.org/wiki/Category:Lists_of_banks_by_country
https://en.wikipedia.org/wiki/List_of_banks_in_South_Africa

Doesn't even say which IDE to use and how to plug the ide into the
database.

https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments
;
https://en.wikipedia.org/wiki/List_of_relational_database_management_systems
;
https://appinventiv.com/blog/top-web-app-database-list/

Doesnt even say how to configure and or design for banking, Its mostly
needed on linux ubunto, windows 11 and macbook os and then tablets and
mobile devices. Doesnt explain how and or where to host the database where
the private and or customenr repository is. Where to build in the bank job
types?

https://www.indeed.com/career-advice/finding-a-job/banking-titles

<https://www.indeed.com/career-advice/finding-a-job/banking-titles>

Account analyst <https://www.indeed.com/q-Account-analyst-jobs.html>: $53,085
per year <https://www.indeed.com/career/account-analyst/salaries>

Account manager <https://www.indeed.com/q-account-manager-jobs.html>
: $60,551 per year <https://www.indeed.com/career/account-manager/salaries>

Accounting assistant
<https://www.indeed.com/q-accounting-assistant-jobs.html>
: $26,930 per year
<https://www.indeed.com/career/accounting-assistant/salaries>

Accounting director <https://www.indeed.com/q-accounting-director-jobs.html>
: $118,598 per year
<https://www.indeed.com/career/account-director/salaries>

Accounting intern <https://www.indeed.com/q-Accounting-intern-jobs.html>
: $56,855 per year
<https://www.indeed.com/career/accounting-intern/salaries>

Accounting specialist
<https://www.indeed.com/q-accounting-specialist-jobs.html>
: $71,492 per year
<https://www.indeed.com/career/accounting-specialist/salaries>

Accounting supervisor
<https://www.indeed.com/q-accounting-supervisor-jobs.html>
: $73,295 per year
<https://www.indeed.com/career/accounting-supervisor/salaries>

Accounts payable clerk
<https://www.indeed.com/q-accounts-payable-clerk-jobs.html>
: $33,864 per year
<https://www.indeed.com/career/accounts-payable-clerk/salaries>

Accounts receivable clerk
<https://www.indeed.com/q-accounts-receivable-clerk-jobs.html>
: $49,325 per year
<https://www.indeed.com/career/accounts-receivable-clerk/salaries>

Actuary <https://www.indeed.com/q-actuary-jobs.html>
: $115,027 per year <https://www.indeed.com/career/actuary/salaries>

Anti-money laundering analyst
<https://www.indeed.com/q-anti-money-laundering-analyst-jobs.html>
: $76,531 per year
<https://www.indeed.com/career/anti-money-laundering-analyst/salaries>

Anti-money laundering manager
<https://www.indeed.com/q-Anti-money-laundering-manager-jobs.html>
: $132,818 per year
<https://www.indeed.com/career/anti-money-laundering-manager/salaries>

Anti-money laundering specialist
<https://www.indeed.com/q-Anti-money-laundering-specialist-jobs.html>
: $76,531 per year
<https://www.indeed.com/career/anti-money-laundering-analyst/salaries>

Assistant bank manager
<https://www.indeed.com/q-assistant-bank-manager-jobs.html>
: $57,222 per year <https://www.indeed.com/career/branch-manager/salaries>

Assistant bookkeeper
<https://www.indeed.com/q-assistant-bookkeeper-jobs.html>
: $37,285 per year
<https://www.indeed.com/career/assistant-bookkeeper/salaries>

Assistant branch manager
<https://www.indeed.com/q-assistant-branch-manager-jobs.html>
: $57,522 per year <https://www.indeed.com/career/branch-manager/salaries>

Assistant controller
<https://www.indeed.com/q-assistant-controller-jobs.html>
: $85,343 per year
<https://www.indeed.com/career/assistant-controller/salaries>

Associate manager <https://www.indeed.com/q-associate-manager-jobs.html>
: $46,528 per year
<https://www.indeed.com/career/associate-manager/salaries>

Audit manager <https://www.indeed.com/q-audit-manager-jobs.html>
: $107,424 per year <https://www.indeed.com/career/audit-manager/salaries>

Auditor <https://www.indeed.com/q-auditor-jobs.html>
: $89,354 per year <https://www.indeed.com/career/auditor/salaries>

Bank teller <https://www.indeed.com/q-bank-teller-jobs.html>
: $24,275 per year <https://www.indeed.com/career/bank-clerk/salaries>

Banking advisor <https://www.indeed.com/q-Banking-advisor-jobs.html>
: $71,655 per year <https://www.indeed.com/career/banking-advisor/salaries>

Bookkeeper <https://www.indeed.com/q-bookkeeper-jobs.html>
: $37,254 per year <https://www.indeed.com/career/bookkeeper/salaries>

Branch coordinator <https://www.indeed.com/q-Branch-coordinator-jobs.html>
: $35,079 per year
<https://www.indeed.com/career/branch-administrator/salaries>

Branch manager <https://www.indeed.com/q-branch-manager-jobs.html>
: $57,522 per year <https://www.indeed.com/career/branch-manager/salaries>

Broker <https://www.indeed.com/q-broker-jobs.html>
: $73,202 per year <https://www.indeed.com/career/broker/salaries>

Brokerage assistant <https://www.indeed.com/q-Brokerage-assistant-jobs.html>
: $40,901 per year
<https://www.indeed.com/career/brokerage-associate/salaries>

Budget analyst <https://www.indeed.com/q-Budget-analyst-jobs.html>
: $80,828 per year <https://www.indeed.com/career/budget-analyst/salaries>

Budget director <https://www.indeed.com/q-budget-director-jobs.html>
: $105,860 per year <https://www.indeed.com/career/budget-director/salaries>

Budget manager <https://www.indeed.com/q-budget-manager-jobs.html>
: $97,514 per year <https://www.indeed.com/career/budget-manager/salaries>

Budget officer <https://www.indeed.com/q-budget-officer-jobs.html>
: $97,514 per year <https://www.indeed.com/career/budget-manager/salaries>

Business banker <https://www.indeed.com/q-business-banker-jobs.html>
: $60,891 per year <https://www.indeed.com/career/business-banker/salaries>

Cash manager <https://www.indeed.com/q-cash-manager-jobs.html>
: $58,136 per year <https://www.indeed.com/career/cash-manager/salaries>

Certified management accountant (CMA)
<https://www.indeed.com/q-Certified-management-accountant-(CMA)-jobs.html>
: $68,317 per year
<https://www.indeed.com/career/management-accountant/salaries>

Certified public accountant (CPA)
<https://www.indeed.com/q-Certified-public-accountant-(CPA)-jobs.html>
: $80,673 per year
<https://www.indeed.com/career/certified-public-accountant/salaries>

Chief financial officer (CFO) <https://www.indeed.com/q-cfo-jobs.html>
: $134,108 per year
<https://www.indeed.com/career/chief-financial-officer/salaries>

Collections supervisor
<https://www.indeed.com/q-Collections-supervisor-jobs.html>
: $55,729 per year
<https://www.indeed.com/career/collection-manager/salaries>

Collector <https://www.indeed.com/q-collector-jobs.html>
: $43,085 per year <https://www.indeed.com/career/collector/salaries>

Compliance auditor <https://www.indeed.com/q-compliance-auditor-jobs.html>
: $69,271 per year
<https://www.indeed.com/career/compliance-auditor/salaries>

Compliance officer <https://www.indeed.com/q-compliance-officer-jobs.html>
: $82,077 per year
<https://www.indeed.com/career/compliance-officer/salaries>

Controller <https://www.indeed.com/q-controller-jobs.html>
: $96,558 per year <https://www.indeed.com/career/controller/salaries>

Corporate accountant
<https://www.indeed.com/q-Corporate-accountant-jobs.html>
: $66,266 per year
<https://www.indeed.com/career/corporate-accountant/salaries>

Cost accountant <https://www.indeed.com/q-cost--accountant-jobs.html>
: $66,922 per year <https://www.indeed.com/career/cost-accountant/salaries>

Cost analyst <https://www.indeed.com/q-cost-analyst-jobs.html>
: $81,985 per year <https://www.indeed.com/career/cost-analyst/salaries>

Cost manager <https://www.indeed.com/q-cost-manager-jobs.html>
: $97,921 per year <https://www.indeed.com/career/cost-manager/salaries>

Credit and collections manager
<https://www.indeed.com/q-credit-and-collections-manager-jobs.html>
: $55,729 per year
<https://www.indeed.com/career/collection-manager/salaries>

Credit assistant <https://www.indeed.com/q-Credit-assistant-jobs.html>
: $36,153 per year <https://www.indeed.com/career/credit-assistant/salaries>

Credit assistant manager
<https://www.indeed.com/q-Credit-assistant-manager-jobs.html>
: $36,153 per year <https://www.indeed.com/career/credit-assistant/salaries>

Credit risk analyst <https://www.indeed.com/q-credit-risk-analyst-jobs.html>
: $92,812 per year <https://www.indeed.com/career/risk-analyst/salaries>

Credit solutions manager
<https://www.indeed.com/q-Credit-solutions-manager-jobs.html>
: $94,595 per year
<https://www.indeed.com/career/solutions-manager/salaries>

Credit specialist <https://www.indeed.com/q-credit-specialist-jobs.html>
: $57,091 per year
<https://www.indeed.com/career/credit-specialist/salaries>

Customer relations representative
<https://www.indeed.com/q-Customer-relations-representative-jobs.html>
: $45,597 per year
<https://www.indeed.com/career/customer-relations-representative/salaries>

Data coordinator <https://www.indeed.com/q-data-coordinator-jobs.html>
: $50,293 per year <https://www.indeed.com/career/data-coordinator/salaries>

Debt collector <https://www.indeed.com/q-debt-collector-jobs.html>
: $56,502 per year <https://www.indeed.com/career/debt-collector/salaries>

Director of financial planning and analysis
<https://www.indeed.com/q-Director-of-financial-planning-and-analysis-jobs.html>
: $129,049 per year
<https://www.indeed.com/career/director-of-financial-planning-and-analysis/salaries>

Director of information technology
<https://www.indeed.com/q-director-of-information-technology-jobs.html>
: $126,130 per year
<https://www.indeed.com/career/director-of-information-technology/salaries>

Division controller <https://www.indeed.com/q-Division-controller-jobs.html>
: $105,143 per year
<https://www.indeed.com/career/division-controller/salaries>

Electronic banking manager
<https://www.indeed.com/q-Electronic-banking-manager-jobs.html>
: $77,380 per year <https://www.indeed.com/career/division-manager/salaries>

Equity analyst <https://www.indeed.com/q-equity-analyst-jobs.html>
: $85,574 per year <https://www.indeed.com/career/equity-analyst/salaries>

Equity partner <https://www.indeed.com/q-Equity-partner-jobs.html>
: $81,322 per year <https://www.indeed.com/career/equity-partner/salaries>

Finance director <https://www.indeed.com/q-finance-director-jobs.html>
: $110,096 per year
<https://www.indeed.com/career/director-of-finance/salaries>

Finance product manager
<https://www.indeed.com/q-finance-project-manager-jobs.html>
: $95,094 per year
<https://www.indeed.com/career/finance-product-manager/salaries>

Financial associate <https://www.indeed.com/q-financial-associate-jobs.html>
: $73,111 per year
<https://www.indeed.com/career/finance-associate/salaries>

Financial management technician
<https://www.indeed.com/q-Financial-management-technician-jobs.html>
: $66,307 per year <https://www.indeed.com/career/finance-manager/salaries>

Foreclosure specialist
<https://www.indeed.com/q-foreclosure-specialist-jobs.html>
: $50,334 per year
<https://www.indeed.com/career/foreclosure-specialist/salaries>

Foreign exchange trader
<https://www.indeed.com/q-Foreign-exchange-trader-jobs.html>
: $96,820 per year
<https://www.indeed.com/career/foreign-exchange-trader/salaries>

Fraud analyst <https://www.indeed.com/q-fraud-analyst-jobs.html>
: $54,815 per year <https://www.indeed.com/career/fraud-analyst/salaries>

Fraud detection analyst
<https://www.indeed.com/q-Fraud-detection-analyst-jobs.html>
: $54,815 per year <https://www.indeed.com/career/fraud-analyst/salaries>

Fraud investigator <https://www.indeed.com/q-fraud-investigator-jobs.html>
: $46,504 per year
<https://www.indeed.com/career/fraud-investigator/salaries>

Fraud manager <https://www.indeed.com/q-fraud-manager-jobs.html>
: $96,232 per year <https://www.indeed.com/career/fraud-manager/salaries>

Funding coordinator <https://www.indeed.com/q-Funding-coordinator-jobs.html>
: $68,950 per year <https://www.indeed.com/career/fund-manager/salaries>

Funding manager <https://www.indeed.com/q-funding-manager-jobs.html>
: $68,950 per year <https://www.indeed.com/career/fund-manager/salaries>
<https://www.indeed.com/q-funding-manager-jobs.html>

Income manager <https://www.indeed.com/q-Income-manager-jobs.html>
: $98,309 per year <https://www.indeed.com/career/income-manager/salaries>

Internal audit manager
<https://www.indeed.com/q-internal-audit-manager-jobs.html>
: $81,558 per year <https://www.indeed.com/career/internal-auditor/salaries>

Internal auditor <https://www.indeed.com/q-internal-auditor-jobs.html>
: $81,558 per year <https://www.indeed.com/career/internal-auditor/salaries>

Investment analyst <https://www.indeed.com/q-investment-analyst-jobs.html>
: $91,140 per year
<https://www.indeed.com/career/investment-analyst/salaries>

Investment banking analyst
<https://www.indeed.com/q-investment-banking-analyst-jobs.html>
: $88,386 per year
<https://www.indeed.com/career/investment-banking-analyst/salaries>

Investment representative
<https://www.indeed.com/q-Investment-representative-jobs.html>
: $55,440 per year
<https://www.indeed.com/career/investment-representative/salaries>

Junior account executive
<https://www.indeed.com/q-Junior-account-executive-jobs.html>
: $90,563 per year
<https://www.indeed.com/career/junior-account-executive/salaries>

Junior financial administrator
<https://www.indeed.com/q-Junior-financial-administrator-jobs.html>
: $33,816 per year
<https://www.indeed.com/career/financial-administrator/salaries>

Junior financial advisor
<https://www.indeed.com/q-Junior-financial-advisor-jobs.html>
: $31,901 per year
<https://www.indeed.com/career/junior-financial-advisor/salaries>

Junior financial analyst
<https://www.indeed.com/q-Junior-financial-analyst-jobs.html>
: $56,367 per year
<https://www.indeed.com/career/junior-financial-analyst/salaries>

Junior financial associate
<https://www.indeed.com/q-Junior-financial-associate-jobs.html>
: $48,837 per year
<https://www.indeed.com/career/junior-financial-planner/salaries>

Junior financial consultant
<https://www.indeed.com/q-Junior-financial-consultant-jobs.html>
: $59,892 per year
<https://www.indeed.com/career/junior-financial-consultant/salaries>

Junior financial controller
<https://www.indeed.com/q-Junior-financial-controller-jobs.html>
: $72,594 per year
<https://www.indeed.com/career/junior-financial-controller/salaries>

Junior financial planner
<https://www.indeed.com/q-Junior-financial-planner-jobs.html>
: $48,837 per year
<https://www.indeed.com/career/junior-financial-planner/salaries>

Junior fund accountant
<https://www.indeed.com/q-Junior-fund-accountant-jobs.html>
: $56,581 per year
<https://www.indeed.com/career/junior-fund-accountant/salaries>

Lending manager <https://www.indeed.com/q-lending-manager-jobs.html>
: $81,265 per year <https://www.indeed.com/career/lending-manager/salaries>

Loan administrator <https://www.indeed.com/q-loan-administrator-jobs.html>
: $61,325 per year
<https://www.indeed.com/career/loan-administrator/salaries>

Loan advisor <https://www.indeed.com/q-Loan-advisor-jobs.html>
: $43,777 per year <https://www.indeed.com/career/loan-advisor/salaries>

Loan coordinator <https://www.indeed.com/q-loan-coordinator-jobs.html>
: $46,659 per year <https://www.indeed.com/career/loan-coordinator/salaries>

Loan processor <https://www.indeed.com/q-loan-processor-jobs.html>
: $52,792 per year <https://www.indeed.com/career/loan-processor/salaries>

Loan supervisor <https://www.indeed.com/q-lab-supervisor-jobs.html>
: $70,223 per year <https://www.indeed.com/career/loan-manager/salaries>

Loss control consultant
<https://www.indeed.com/q-loss-control-consultant-jobs.html>
: $75,725 per year
<https://www.indeed.com/career/loss-control-consultant/salaries>

Loss mitigation specialist
<https://www.indeed.com/q-Loss-mitigation-specialist-jobs.html>
: $55,168 per year
<https://www.indeed.com/career/loss-prevention-manager/salaries>

Loss prevention manager
<https://www.indeed.com/q-Loss-prevention-manager-jobs.html>
: $55,168 per year
<https://www.indeed.com/career/loss-prevention-manager/salaries>

Loss prevention officer
<https://www.indeed.com/q-loss-prevention-officer-jobs.html>
: $46,389 per year
<https://www.indeed.com/career/loss-prevention-officer/salaries>

Mortgage advisor <https://www.indeed.com/career/mortgage-advisor/salaries>
: $60,071 per year <https://www.indeed.com/career/mortgage-advisor/salaries>

Mortgage closer <https://indeed.com/q-mortgage-closer-jobs.html>
: $56,940 per year <https://www.indeed.com/career/mortgage-closer/salaries>

Mortgage consultant <https://www.indeed.com/q-Mortgage-consultant-jobs.html>
: $57,196 per year
<https://www.indeed.com/career/mortgage-consultant/salaries>

Mortgage loan originator
<https://www.indeed.com/q-mortgage-loan-originator-jobs.html>
: $157,009 per year
<https://www.indeed.com/career/mortgage-loan-originator/salaries>

Mortgage processor <https://www.indeed.com/q-mortgage-processor-jobs.html>
: $57,817 per year
<https://www.indeed.com/career/mortgage-processor/salaries>

Mortgage underwriter
<https://www.indeed.com/q-Mortgage-underwriter-jobs.html>
: $89,226 per year
<https://www.indeed.com/career/mortgage-underwriter/salaries>

Notary <https://www.indeed.com/q-notary-jobs.html>
: $34,563 per year <https://www.indeed.com/career/notary-public/salaries>

Payment processor <https://www.indeed.com/q-Payment-processor-jobs.html>
: $33,655 per year
<https://www.indeed.com/career/payment-processor/salaries>

Payroll analyst <https://www.indeed.com/q-payroll-analyst-jobs.html>
: $54,456 per year <https://www.indeed.com/career/payroll-analyst/salaries>

Portfolio administrator
<https://www.indeed.com/q-Portfolio-administrator-jobs.html>
: $54,374 per year
<https://www.indeed.com/career/portfolio-administrator/salaries>

Portfolio advisor <https://www.indeed.com/q-Portfolio-advisor-jobs.html>
: $54,374 per year
<https://www.indeed.com/career/portfolio-administrator/salaries>

Portfolio manager <https://www.indeed.com/q-portfolio-manager-jobs.html>
: $100,399 per year
<https://www.indeed.com/career/portfolio-manager/salaries>

Property accountant <https://www.indeed.com/q-property-accountant-jobs.html>
: $65,269 per year
<https://www.indeed.com/career/property-accountant/salaries>

Regional director <https://www.indeed.com/q-Regional-director-jobs.html>
: $103,954 per year
<https://www.indeed.com/career/regional-director/salaries>

Risk analyst <https://www.indeed.com/q-Risk-analyst-jobs.html>
: $92,812 per year <https://www.indeed.com/career/risk-analyst/salaries>

Risk and compliance investigator
<https://www.indeed.com/q-Risk-and-compliance-investigator-jobs.html>
: $92,234 per year
<https://www.indeed.com/career/risk-and-compliance-investigator/salaries>

Risk manager <https://www.indeed.com/q-risk-manager-jobs.html>
: $118,304 per year <https://www.indeed.com/career/risk-manager/salaries>

Risk specialist <https://www.indeed.com/q-risk-specialist-jobs.html>
: $106,493 per year
<https://www.indeed.com/career/financial-modeler/salaries>

Senior analyst <https://www.indeed.com/q-senior-analyst-jobs.html>
: $97,861 per year <https://www.indeed.com/career/senior-analyst/salaries>

Senior assistant bank manager
<https://www.indeed.com/q-Senior-assistant-bank-manager-jobs.html>
: $31,828 per year
<https://www.indeed.com/career/senior-assistant-manager/salaries>

Senior bank official
<https://www.indeed.com/q-Senior-bank-official-jobs.html>
: $45,487 per year
<https://www.indeed.com/career/senior-bank-official/salaries>

Senior tax manager <https://www.indeed.com/q-senior-tax-manager-jobs.html>
: $121,830 per year
<https://www.indeed.com/career/senior-tax-manager/salaries>

Tax accountant <https://www.indeed.com/q-tax-accountant-jobs.html>
: $65,450 per year <https://www.indeed.com/career/tax-accountant/salaries>

Tax advisor <https://www.indeed.com/q-Tax-advisor-jobs.html>
: $41,619 per year <https://www.indeed.com/career/tax-advisor/salaries>

Tax consultant <https://www.indeed.com/q-tax-consultant-jobs.html>
: $63,627 per year <https://www.indeed.com/career/tax-consultant/salaries>

Tax examiner <https://www.indeed.com/q-tax-examiner-jobs.html>
: $37,117 per year <https://www.indeed.com/career/tax-examiner/salaries>

Tax preparer <https://www.indeed.com/q-tax-preparer-jobs.html>
: $38,765 per year <https://www.indeed.com/career/tax-preparer/salaries>

Tax senior <https://www.indeed.com/q-tax-senior-jobs.html>
: $79,280 per year <https://www.indeed.com/career/tax-senior/salaries>

Tax specialist <https://www.indeed.com/q-tax-specialist-jobs.html>
: $62,969 per year <https://www.indeed.com/career/tax-specialist/salaries>

Tax supervisor <https://www.indeed.com/q-Tax-supervisor-jobs.html>
: $121,149 per year <https://www.indeed.com/career/tax-manager/salaries>

Treasurer <https://www.indeed.com/q-treasurer-jobs.html>
: $78,849 per year <https://www.indeed.com/career/treasurer/salaries>

Treasury analyst <https://www.indeed.com/q-treasury-analyst-jobs.html>
: $74,337 per year <https://www.indeed.com/career/treasury-analyst/salaries>

Treasury manager <https://www.indeed.com/q-treasury-manager-jobs.html>
: $118,925 per year
<https://www.indeed.com/career/treasury-manager/salaries>

Treasury management officer
<https://www.indeed.com/q-treasury-management-officer-jobs.html>
: $118,925 per year
<https://www.indeed.com/career/treasury-manager/salaries>

Trust manager <https://www.indeed.com/q-trust-manager-jobs.html>
: $102,865 per year <https://www.indeed.com/career/trust-manager/salaries>

Trustee <https://www.indeed.com/q-trustee-jobs.html>
: $75,689 per year <https://www.indeed.com/career/trustee/salaries>

Underwriter <https://www.indeed.com/q-underwriter-jobs.html>
: $79,260 per year <https://www.indeed.com/career/underwriter/salaries>

Vice president of finance
<https://www.indeed.com/q-vice-president-of-finance-jobs.html>
: $161,639 per year
<https://www.indeed.com/career/vice-president-of-finance/salaries>



Regards
John Patrick Oldfield
Quantitative Research Analyst
Bcom
Tefl
Sc
Ceh

**Comment by ZacharyRiffle** [comment]
Hi again John. I know you are frustrated with the lack of available financial server system information and tooling to create and pay for services. However, we cannot add these job postings to our Financial Services page ([Microsoft Cloud for Financial Services](https://microsoft.github.io/PartnerResources/industry/financial-services/microsoft-cloud-for-financial-services)). We also cannot help you send a prize question to a local school or university to design a bank dashboard or interface. If you have questions about Microsoft products, services, or our Partner Resources repository, please let us know. Until then, this issue remains closed.

**Comment by johnpatrickoldfield** [comment]
Yes I am already aware of that, I'm way past frustrated, frustration was a
2010 to 2020 issue. Do any financial personal that actually work at
microsoft it seems like there's a lot of talk about money and or finances
and no actual money and or bank finances available and or services
availability and the more I apply to jobs at microsoft the more useless
responses I get from the supposed job server and it's not just microsoft
thats been picky with jobs and cash flow allowances, employment equity
policy is trash on my end of the system. Like recycled trash.  It's all
back end server side permissions requirements that I need or fully loaded
bank card requirements with the cards availability otherwise redesign of
the ux andouille interfaces for inclusion of the missing financial
categories and missing financial dashboards and then slightly less
simplistic dashboards and slightly mode complicated tools that are not
necessarily scripting from scratch for total functional algorithms and or
coe structures on the front end. At the moment Im seeing lits of hyperlinks
and coding exercises where its a coding repository otherwise a
questionnaire on coding repository coding instructions with no solutions
template however nothing financially useful. Then won't allow me to work as
the coding functions, modules, interface knowledge has been mostly left out
of the education system and I end up requesting design requirements and
solution requirements theory instead of practical and or accessible.
There's this n - able team that's trying to advertise to me, any idea how
to push the requests through there? https://www.n-able.com/ ;
https://www.n-able.com/company

What about the senior engineers?  What about the distinguished engineers
and or distinguished engineers? Where are these personal job description
types? It's literally lagging on a financial pull request to the
relevant bank and no one appears to be able to sort it out for me with the
correct referral and or correct deferral and then do the interim financial
calculations and keep pushing to learning exercises instead of earning
exercises. I have to keep filling in the same types of forms. There's a
huge difference between a learning exercise and an earning exercise which
the financial regulator that monitors the workflows cannot seem to
distinguish from my side of the receiver function.
https://www.levels.fyi/?compare=Microsoft,Amazon,Oracle,Discovery&track=Software%20Engineer
;
https://docs.google.com/document/d/1TYhDOLfFSrkzfKzpp7Y-0_GMsc7lWeoWhhPuqn5I3_4/edit

SDE
59
<https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/SDE/>
60 <https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/60/>
SDE II
61
<https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/SDE-II/>
62 <https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/62/>
Senior SDE
63
<https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/Senior-SDE/>
64 <https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/64/>
Principal SDE
65
<https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/Principal-SDE/>
66 <https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/66/>
67 <https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/67/>
Partner
68
<https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/Partner/>
69 <https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/69/>
70
Distinguished Engineer
<https://www.levels.fyi/company/Microsoft/salaries/Software-Engineer/70/>
80
Technical Fellow

**Comment by ZacharyRiffle** [comment]
I’m sorry you are dissatisfied with our financial services, job opportunities, and/or the education system. We do not know the n-able team and our team is not senior distinguished engineers or product designers. I hope you are able to find what you are looking for. This is my last comment, and the issue will remain closed.
