### ISSUE TITLE
Move Azure Sentinel Learning Plan Resources into Modern Work & Security

### ISSUE THREAD

**Issue by fpachmayr** [microsoft/PartnerResources#67]
Should this be moved from Azure Infra to Modern Work & Security to match current solution area taxonomy?
https://github.com/microsoft/PartnerResources/blob/main/LearningPlanResources/Azure/Infrastructure/Threat%20Protection.md

**Comment by Jeep-Girl** [comment]
Need the plan named Threat Protection.md under Azure\Infrastructure to be merged in with the existing Azure Sentinel Learning Plan in Modern Work & Security\Security. 

Verify then Add content from existing Threat Protection plan to the Azure Sentinel plan.

**Comment by bhitney** [comment]
Not sure if this is still relevant, will close for now, please reopen if needed.
