### ISSUE TITLE
Where did all of the Azure documentation go?

### ISSUE THREAD

**Issue by elucht** [microsoft/PartnerResources#730]
Question on: https://github.com/microsoft/PartnerResources/tree/master/_docs/Azure/index.md

All of the documentation for Azure seems to have been removed.  Can we get this added back?  All that is available is Azure IOT

**Comment by ZacharyRiffle** [comment]
Hello Erik! The Azure documentation has been integrated into our existing Academies. You can locate the documentation under the “Resources” section within the relevant Academy.
