### ISSUE TITLE
Links to old content from 2022

### ISSUE THREAD

**Issue by DeanGross144** [microsoft/PartnerResources#776]
Question on: https://github.com/microsoft/PartnerResources/tree/master/_docs/Skilling/Security Academy/Academies/Purview Academy.md
All of these links point to content that is 2 years old and much has changed since then, can we please get some updates?

**Comment by ZacharyRiffle** [comment]
Hi Dean -- the Security Academy will undergo an overhaul throughout July and into August. During this overhaul, we'll review and update outdated content.
