### ISSUE TITLE
Rename "OSS DB to Azure.md" to "Azure Database for MySQL, MariaDB and Postgres.md"

### ISSUE THREAD

**Issue by sumitsengupta** [microsoft/PartnerResources#98]
The top level markdown files under "Data, Analytics and AI" are named as per the commonly known service names in Azure.

"OSS DB to Azure" sounds like a migration to Azure. Besides, "OSS DB" is more of a colloquial term internally used.

So perhaps rename the md file/

**Comment by bhitney** [comment]
Good idea -- done.  Thanks!
